<?php $current_folder_name = basename(dirname(__FILE__));
$path_to_images = MBT_MAXI_PATTERNS_URL . $current_folder_name . '/images/';?>
<!-- wp:maxi-blocks/container-maxi {"maxi-version-current":"1.8.8","maxi-version-origin":"1.4.1","blockStyle":"light","isFirstOnHierarchy":true,"uniqueID":"container-maxi-3eadb3dc-u","customLabel":"Navigation Menu Light NML-PRO-15","border-style-general":"solid","border-top-width-general":3,"border-right-width-general":0,"border-bottom-width-general":3,"border-left-width-general":0,"border-sync-width-general":"axis","max-width-unit-xxl":"px","max-width-unit-xl":"px","max-width-unit-l":"%","max-width-xxl":"1690","max-width-xl":"1170","max-width-l":"90","width-unit-l":"px","width-l":"1170","width-m":"1000","width-s":"700","width-xs":"460","padding-top-general":"30","padding-top-xxl":"50","padding-top-xl":"30","padding-top-m":"20","padding-top-s":"10","padding-bottom-general":"30","padding-bottom-xxl":"50","padding-bottom-xl":"30","padding-bottom-m":"20","padding-bottom-s":"10","padding-sync-general":"axis","z-index-general":3,"advanced-css-general":"nav .wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close ul {\n    -moz-column-gap: initial;\n    column-gap: initial;\n    row-gap: initial;\n}\n.wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close .wp-block-navigation__submenu-container {\npadding:0px 10px 0;\n}\n.wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close{\npadding:2rem 5%;\n}"} -->
<section class="wp-block-maxi-blocks-container-maxi maxi-block maxi-container-block maxi-light container-maxi-3eadb3dc-u" id="container-maxi-3eadb3dc-u"><div class="maxi-background-displayer"><div class="maxi-background-displayer__layer maxi-background-displayer__1"></div></div><!-- wp:maxi-blocks/row-maxi {"maxi-version-current":"1.8.8","maxi-version-origin":"1.4.1","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"row-maxi-9744c53c-u","customLabel":"Row_1","row-pattern-general":"1-3","row-pattern-m":"1-1-1","row-pattern-s":"1-2-2","row-pattern-xs":"1-1-1","max-width-unit-xxl":"px","max-width-unit-xl":"px","max-width-unit-l":"%","max-width-xxl":"1690","max-width-xl":"1170","max-width-l":"90","flex-wrap-general":"nowrap","column-gap-xl":0} -->
<div class="wp-block-maxi-blocks-row-maxi maxi-block maxi-row-block maxi-light row-maxi-9744c53c-u" id="row-maxi-9744c53c-u"><!-- wp:maxi-blocks/column-maxi {"maxi-version-current":"1.8.8","maxi-version-origin":"1.4.1","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"column-maxi-9324b1ef-u","customLabel":"Column_1","column-size-general":25,"column-size-xl":25,"column-size-m":100,"column-size-s":50,"column-size-xs":70,"column-fit-content-general":true,"justify-content-general":"center"} -->
<div class="wp-block-maxi-blocks-column-maxi maxi-block maxi-column-block maxi-light column-maxi-9324b1ef-u" id="column-maxi-9324b1ef-u"><!-- wp:maxi-blocks/image-maxi {"maxi-version-current":"1.8.8","maxi-version-origin":"1.7.0","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"image-maxi-81c468d6-u","customLabel":"Image logo size:350x104px-NML-PRO-15","mediaID":16625,"mediaURL":"<?php echo $path_to_images; ?>NML-PRO-15-logo-1708617778-1899485679-1708617778-588537302.webp","mediaAlt":"NML-PRO-15-logo-1708617778-1899485679","altSelector":"title","mediaWidth":350,"mediaHeight":104,"width-general":"150","width-xxl":"170","width-xl":"150","width-xs":"130","margin-left-general":"0","margin-sync-general":"none"} -->
<figure class="wp-block-maxi-blocks-image-maxi maxi-block maxi-image-block maxi-light image-maxi-81c468d6-u" id="image-maxi-81c468d6-u"><div class="maxi-hover-preview maxi-image-block-wrapper"><img class="maxi-image-block__image wp-image-16625" src="<?php echo $path_to_images; ?>NML-PRO-15-logo-1708617778-1899485679-1708617778-588537302.webp" alt="NML-PRO-15-logo-1708617778-1899485679" width="350" height="104"/></div></figure>
<!-- /wp:maxi-blocks/image-maxi --></div>
<!-- /wp:maxi-blocks/column-maxi -->

<!-- wp:maxi-blocks/column-maxi {"maxi-version-current":"1.8.8","maxi-version-origin":"1.4.1","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"column-maxi-8bdeaaac-u","customLabel":"Column_2","column-size-general":75,"column-size-xxl":100,"column-size-xl":100,"column-size-m":100,"padding-left-general":"20","padding-left-xxl":"30","padding-left-xl":"20","padding-sync-general":"none","z-index-general":2,"advanced-css-general":"","advanced-css-s":"nav ul{ \ncolumn-gap:20px;\nrow-gap:10px;\njustify-content: flex-start;\n}","justify-content-general":"center"} -->
<div class="wp-block-maxi-blocks-column-maxi maxi-block maxi-column-block maxi-light column-maxi-8bdeaaac-u" id="column-maxi-8bdeaaac-u"><!-- wp:navigation {"ref":18020,"icon":"menu","hasIcon":false,"layout":{"type":"flex","justifyContent":"right","orientation":"horizontal"},"style":{"spacing":{"blockGap":"0"}}} /--></div>
<!-- /wp:maxi-blocks/column-maxi --></div>
<!-- /wp:maxi-blocks/row-maxi --></section>
<!-- /wp:maxi-blocks/container-maxi -->
