<?php $current_folder_name = basename(dirname(__FILE__));
$path_to_images = MBT_MAXI_PATTERNS_URL . $current_folder_name . '/images/';?>
<!-- wp:maxi-blocks/container-maxi {"maxi-version-current":"1.8.1","maxi-version-origin":"1.4.1","blockStyle":"light","isFirstOnHierarchy":true,"uniqueID":"container-maxi-5f9a940d-u","customLabel":"Navigation Menu Light NML-PRO-17","border-style-general":"solid","border-top-width-general":3,"border-right-width-general":0,"border-bottom-width-general":3,"border-left-width-general":0,"border-sync-width-general":"axis","max-width-unit-xxl":"px","max-width-unit-xl":"px","max-width-unit-l":"%","max-width-xxl":"1690","max-width-xl":"1170","max-width-l":"90","width-unit-l":"px","width-l":"1170","width-m":"1000","width-s":"700","width-xs":"460","padding-top-general":"30","padding-top-xxl":"50","padding-top-xl":"30","padding-top-m":"20","padding-top-s":"10","padding-bottom-general":"30","padding-bottom-xxl":"50","padding-bottom-xl":"30","padding-bottom-m":"20","padding-bottom-s":"10","padding-sync-general":"axis","z-index-general":3,"advanced-css-general":"nav .wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close ul {\n    -moz-column-gap: initial;\n    column-gap: initial;\n    row-gap: initial;\n}\n.wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close .wp-block-navigation__submenu-container {\npadding:0px 10px 0;\n}\n.wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close{\npadding:2rem 5%;\n}","advanced-css-xl":"nav .wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close ul {\n    -moz-column-gap: initial;\n    column-gap: initial;\n    row-gap: initial;\n}\n.wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close .wp-block-navigation__submenu-container {\npadding:0px 10px 0;\n}\n.wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close{\npadding:2rem 5%;\n}","advanced-css-s":"nav.wp-block-navigation {\njustify-content:flex-end!important;\n}\nnav .wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close ul {\n    -moz-column-gap: initial;\n    column-gap: initial;\n    row-gap: initial;\n}\n.wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close .wp-block-navigation__submenu-container {\npadding:0px 10px 0;\n}\n.wp-block-navigation__responsive-container.has-modal-open .wp-block-navigation__responsive-close{\npadding:2rem 5%;\n}"} -->
<section class="wp-block-maxi-blocks-container-maxi maxi-block maxi-container-block maxi-light container-maxi-5f9a940d-u" id="container-maxi-5f9a940d-u"><div class="maxi-background-displayer"><div class="maxi-background-displayer__layer maxi-background-displayer__1"></div></div><!-- wp:maxi-blocks/row-maxi {"maxi-version-current":"1.8.1","maxi-version-origin":"1.4.1","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"row-maxi-5bca3684-u","customLabel":"Row_1","row-pattern-general":"3 columns","row-pattern-m":"1-1-1","row-pattern-s":"1-2-2","max-width-unit-xxl":"px","max-width-unit-xl":"px","max-width-unit-l":"%","max-width-xxl":"1690","max-width-xl":"1170","max-width-l":"90","flex-wrap-general":"nowrap","column-gap-general":0,"column-gap-xl":0} -->
<div class="wp-block-maxi-blocks-row-maxi maxi-block maxi-row-block maxi-light row-maxi-5bca3684-u" id="row-maxi-5bca3684-u"><!-- wp:maxi-blocks/column-maxi {"maxi-version-current":"1.8.1","maxi-version-origin":"1.4.1","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"column-maxi-ffa7b225-u","customLabel":"Column_1","column-size-general":25,"column-size-xl":25,"column-size-m":40,"column-size-s":50,"column-size-xs":70,"column-fit-content-general":true,"column-fit-content-xl":true,"padding-right-m":"20","padding-right-xs":"10","padding-sync-xl":"all","padding-sync-m":"none","justify-content-general":"center"} -->
<div class="wp-block-maxi-blocks-column-maxi maxi-block maxi-column-block maxi-light column-maxi-ffa7b225-u" id="column-maxi-ffa7b225-u"><!-- wp:maxi-blocks/image-maxi {"maxi-version-current":"1.8.1","maxi-version-origin":"1.7.0","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"image-maxi-cc999f3b-u","customLabel":"Image logo size:350x114px-NML-PRO-17","mediaID":16621,"mediaURL":"<?php echo $path_to_images; ?>NML-PRO-17-logo-1708617779-1367745935-1708617779-395660659.webp","mediaAlt":"NML-PRO-17-logo-1708617779-1367745935","altSelector":"title","mediaWidth":350,"mediaHeight":114,"width-general":"150","width-xxl":"170","width-xl":"150","width-xs":"115","margin-left-general":"0","margin-sync-general":"none"} -->
<figure class="wp-block-maxi-blocks-image-maxi maxi-block maxi-image-block maxi-light image-maxi-cc999f3b-u" id="image-maxi-cc999f3b-u"><div class="maxi-hover-preview maxi-image-block-wrapper"><img class="maxi-image-block__image wp-image-16621" src="<?php echo $path_to_images; ?>NML-PRO-17-logo-1708617779-1367745935-1708617779-395660659.webp" alt="NML-PRO-17-logo-1708617779-1367745935" width="350" height="114"/></div></figure>
<!-- /wp:maxi-blocks/image-maxi --></div>
<!-- /wp:maxi-blocks/column-maxi -->

<!-- wp:maxi-blocks/column-maxi {"maxi-version-current":"1.8.1","maxi-version-origin":"1.4.1","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"column-maxi-547f9fea-u","customLabel":"Column_2","column-size-general":100,"column-size-xl":100,"column-fit-content-m":true,"padding-right-general":"20","padding-right-xxl":"30","padding-right-xl":"20","padding-right-m":"0","padding-left-general":"20","padding-left-xxl":"30","padding-left-xl":"20","padding-left-xs":"10","padding-sync-general":"axis","padding-sync-xl":"axis","padding-sync-m":"none","z-index-general":2,"advanced-css-general":"","advanced-css-s":"nav ul{ \ncolumn-gap:20px;\nrow-gap:10px;\njustify-content: flex-start;\n}","justify-content-general":"center","order-m":3} -->
<div class="wp-block-maxi-blocks-column-maxi maxi-block maxi-column-block maxi-light column-maxi-547f9fea-u" id="column-maxi-547f9fea-u"><!-- wp:navigation {"icon":"menu","layout":{"type":"flex","justifyContent":"center","orientation":"horizontal"},"style":{"spacing":{"blockGap":"0"}}} /--></div>
<!-- /wp:maxi-blocks/column-maxi -->

<!-- wp:maxi-blocks/column-maxi {"maxi-version-current":"1.8.1","maxi-version-origin":"1.4.1","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"column-maxi-f18ca7f4-u","customLabel":"Column_3","column-size-general":33.33,"column-size-xl":33.33,"column-size-m":100,"column-size-s":20,"column-size-xs":100,"column-fit-content-general":true,"column-fit-content-xl":true,"column-fit-content-xs":false,"margin-left-m":"auto","margin-sync-xl":"all","margin-sync-m":"none","justify-content-general":"center"} -->
<div class="wp-block-maxi-blocks-column-maxi maxi-block maxi-column-block maxi-light column-maxi-f18ca7f4-u" id="column-maxi-f18ca7f4-u"><!-- wp:maxi-blocks/search-maxi {"maxi-version-current":"1.8.1","maxi-version-origin":"1.7.0","blockStyle":"light","isFirstOnHierarchy":false,"uniqueID":"search-maxi-f313cc14-u","customLabel":"Search_1","border-style-general":"solid","border-top-left-radius-general":999,"border-top-right-radius-general":999,"border-bottom-right-radius-general":999,"border-bottom-left-radius-general":999,"border-top-width-general":4,"border-right-width-general":4,"border-bottom-width-general":4,"border-left-width-general":4,"box-shadow-palette-color-general-hover":8,"box-shadow-vertical-general-hover":10,"box-shadow-blur-general-hover":20,"box-shadow-status-hover":true,"width-unit-xl":"px","width-unit-xs":"%","width-general":"200","width-xxl":"270","width-xl":"200","width-m":"180","width-s":"150","width-xs":"100","input-font-size-general":16,"input-font-size-xxl":20,"input-font-size-xl":16,"input-line-height-unit-general":"%","input-line-height-general":130,"input-border-style-general":"none","input-border-top-width-general":2,"input-border-right-width-general":2,"input-border-bottom-width-general":2,"input-border-left-width-general":2,"input-padding-top-xxl":"12","input-padding-top-xl":"8","input-padding-right-xxl":"40","input-padding-right-xl":"35","input-padding-bottom-xxl":"12","input-padding-bottom-xl":"8","input-padding-left-general":"15","input-padding-sync-general":"none","input-background-palette-opacity-general":0,"input-background-color-general":"rgba(255, 255, 255, 0)","button-padding-top-general":"0","button-padding-right-general":"0","button-padding-bottom-general":"0","button-padding-left-general":"0","button-padding-sync-xl":"all","button-background-palette-color-general":1,"button-background-palette-opacity-general":0,"button-background-color-general":"rgba(255, 255, 255, 0)","button-border-top-left-radius-general":999,"button-border-top-right-radius-general":999,"button-border-bottom-right-radius-general":999,"button-border-bottom-left-radius-general":999,"icon-content":"\u003csvg viewBox=\u00220 0 36.1 36.1\u0022 height=\u002264px\u0022 width=\u002264px\u0022 class=\u0022magnifying-glass-41-shape-maxi-svg\u0022\u003e\u003cpath data-fill data-hover-fill fill=\u0022var(\u002d\u002dmaxi-light-icon-fill,rgba(var(\u002d\u002dmaxi-light-color-5,0,0,0),1))\u0022 d=\u0022M35.2 32.1l-7.9-7.9c1.9-2.6 3-5.7 3-8.9 0-8.3-6.8-15-15-15s-15 6.8-15 15 6.8 15 15 15c3.2 0 6.4-1 8.9-3l7.9 7.9c.4.4 1 .7 1.6.7s1.2-.2 1.6-.7.7-1 .7-1.6-.3-1.1-.8-1.5zm-19.9-6.2c-5.8 0-10.6-4.8-10.6-10.6S9.4 4.7 15.3 4.7s10.6 4.8 10.6 10.6-4.8 10.6-10.6 10.6z\u0022 data-fill\u003e\u003c/path\u003e\u003c/svg\u003e","icon-width-general":"20","icon-width-xxl":"25","icon-width-xl":"20","icon-fill-palette-color":5,"icon-fill-palette-color-hover":6,"icon-status-hover":true} -->
<div class="wp-block-maxi-blocks-search-maxi maxi-block maxi-search-block maxi-light search-maxi-f313cc14-u maxi-search-block--icon-right" id="search-maxi-f313cc14-u"><input class="maxi-search-block__input" type="text" placeholder="Search..." required/><div class="maxi-search-block__button"><div class="maxi-search-block__button__icon maxi-search-block__button__default-icon"><svg class="magnifying-glass-41-shape-maxi-svg" width="64px" height="64px" viewBox="0 0 36.1 36.1"><path d="M35.2 32.1l-7.9-7.9c1.9-2.6 3-5.7 3-8.9 0-8.3-6.8-15-15-15s-15 6.8-15 15 6.8 15 15 15c3.2 0 6.4-1 8.9-3l7.9 7.9c.4.4 1 .7 1.6.7s1.2-.2 1.6-.7.7-1 .7-1.6-.3-1.1-.8-1.5zm-19.9-6.2c-5.8 0-10.6-4.8-10.6-10.6S9.4 4.7 15.3 4.7s10.6 4.8 10.6 10.6-4.8 10.6-10.6 10.6z" fill="var(--maxi-light-icon-fill,rgba(var(--maxi-light-color-5,0,0,0),1))" data-hover-fill="" data-fill=""></path></svg></div></div></div>
<!-- /wp:maxi-blocks/search-maxi --></div>
<!-- /wp:maxi-blocks/column-maxi --></div>
<!-- /wp:maxi-blocks/row-maxi --></section>
<!-- /wp:maxi-blocks/container-maxi -->
